# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: main-ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - run: yarn install --frozen-lockfile
    - run: yarn 



    - name: DockerHub Login
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -f Dockerfile -t ${{ secrets.DOCKER_ID }}/${{ secrets.FOODIFUL_FRONT }} . platform=linux/amd64
        docker push ${{ secrets.DOCKER_ID }}/${{ secrets.FOODIFUL_FRONT }}
    
    
