# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3

    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - run: yarn install --frozen-lockfile
    - run: yarn 

    
    # Docker 이미지 빌드
    - name: Docker image build
      run: |
        docker build -t ${{ secrets.DOCKER_ID }}/${{ secrets.FOODIFUL_FRONT }}  -f ./Dockerfile . --platform=linux/amd64
    - name: Docker image push
      run: |
        docker push ${{ secrets.DOCKER_ID }}/${{ secrets.FOODIFUL_FRONT }}
